coder2/config/routes.rb
Rails.application.routes.draw do

  # root 'users#index'
  root 'site#home'
  devise_for :users
  resources :services
  resources :products
  resources :users

  #   get 'products/:id' => 'catalog#view'

  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

end

coder2/app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
end

coder2/app/models/service.rb
class Service < ActiveRecord::Base
	belongs_to :user
end

coder2/app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_many :products 
  has_many :services

end

coder2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

coder2/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.fetch(:product, {})
    end
end

coder2/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  def index
    @services = Service.all
  end

  def show
  end

  def new
    @service = Service.new
  end

  def edit
  end

  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_service
      @service = Service.find(params[:id])
    end

    def service_params
      params.fetch(:service, {})
    end
end

coder2/app/controllers/site_controller.rb
class SiteController < ApplicationController

  def home
  	render layout: false
  end
end

coder2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:user, :email, :new_email, :username, :new_password, :new_password_confirmation, :address, :about, :ceo, :avatar, :city, :phone, :country)
    end
end

coder2/app/helpers/application_helper.rb
module ApplicationHelper
end

coder2/app/helpers/products_helper.rb
module ProductsHelper
end

coder2/app/helpers/services_helper.rb
module ServicesHelper
end

coder2/app/helpers/users_helper.rb
module UsersHelper
end

coder2/app/views/layouts/_header.html.haml
%nav.navbar.navbar-light.bg-faded
  %button.navbar-toggler.hidden-sm-up{"data-target" => "#exCollapsingNavbar2", "data-toggle" => "collapse", :type => "button"}
    ☰
  
  #exCollapsingNavbar2.collapse.navbar-toggleable-xs
    %ul.nav.navbar-nav
      %li= link_to 'Home --', root_path, class: 'nav-item'
      %li= link_to 'Products --', products_path, class: 'nav-item'
      %li= link_to 'Services', services_path, class: 'nav-item'
      
      %form.form-inline.pull-xs-right
        = text_field_tag :search, params[:search]
        %button.btn.btn-success-outline{:type => "submit"} Search

coder2/app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %title
      SORA

  %body
    #wrap
      = render 'layouts/header'

    .container
      .notice
        = notice
      .alert
        = alert
      
      = yield

  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  
  = csrf_meta_tags


:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74680816-1', 'auto');
  ga('send', 'pageview');

coder2/app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

coder2/app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

coder2/app/views/products/index.html.haml
%h1 Listing products

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td= link_to 'Show', product
        %td= link_to 'Edit', edit_product_path(product)
        %td= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Product', new_product_path

coder2/app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

coder2/app/views/products/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path

coder2/app/views/services/_form.html.haml
= form_for @service do |f|
  - if @service.errors.any?
    #error_explanation
      %h2= "#{pluralize(@service.errors.count, "error")} prohibited this service from being saved:"
      %ul
        - @service.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

coder2/app/views/services/edit.html.haml
%h1 Editing service

= render 'form'

= link_to 'Show', @service
\|
= link_to 'Back', services_path

coder2/app/views/services/index.html.haml
%h1 Listing services

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @services.each do |service|
      %tr
        %td= link_to 'Show', service
        %td= link_to 'Edit', edit_service_path(service)
        %td= link_to 'Destroy', service, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Service', new_service_path

coder2/app/views/services/new.html.haml
%h1 New service

= render 'form'

= link_to 'Back', services_path

coder2/app/views/services/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_service_path(@service)
\|
= link_to 'Back', services_path

coder2/app/views/site/home.html.haml
%html.full{:lang => "en"}/
%head
  %title

  = stylesheet_link_tag "application", media: "all"
  = csrf_meta_tags

  - provide :title, 'SORA Splash'

/ .col-xs-12
/   .card.card-inverse{:style => "background-color: DarkGreen; border-color: DarkGreen"}
/     .card-block
/       %h1.card-title What Do You Need?
/       %p.card-text Resource Search Engine Based on Adam Smiths The Wealth of Nations
/       %a.btn.btn-primary{:href => "#"} Button

/     .row
/       %form.col-center
/         = form_tag :controller => 'users', :action => 'index', :method => 'get' do 
/           %p
/           = text_field_tag :search, params[:search], :placeholder => "Type Dish Here"
/           %br
/           %button.btn.btn-warning{:type => "submit"} Search

#body
Social Resource Allocation

.col-xs-12
  .col-md-4
  .col-md-8
    .card.card-inverse{:style => "background-color: DarkGreen; border-color: DarkGreen"}
      .card-block  
        %h1.card-title What Do You Need?
        %p.card-text Resource Search Engine Based on Adam Smiths The Wealth of Nations
        %form{action: "#{new_user_path}", method: 'get'}
          %p.card-text
            I need 
            / = raw t 'splash.need'
            = text_field_tag 'search_for', nil, :input_html => { :value => "How?" }, autofocus: true
            = select_tag "kind", "<option>In HCM</option> <option>In Hanoi</option> <option>In Da Nang</option>".html_safe, {:style => "background-color: DarkGreen"}
            = submit_tag 'Search!', class: 'code btn btn-default', name: nil, class: 'btn btn-primary'
          %br
          %br
          %p.card-text
            "I need an English teacher!"
            / = raw t 'splash.search1'
            %br
            %br
            "I need a bread supplier!"
            / = raw t 'splash.search2'
            %br
            %br
            "I need Java web developers"
            / = raw t 'splash.search3'


#login.modal.fade{tabindex: "-1", role: "dialog", aria: {labelledby: "Password Reset", hidden: true}}
  .modal-dialog
    .modal-content
      .col-xs-12.col-sm-12.col-md-12
        .modal-header
          %button.close{type: "button", data: {dismiss: "modal"}, aria: {hidden: true}} &times;
          %h4.modal-title Login
        .modal-body
          .col-xs-12.col-sm-12.col-md-12
            / = simple_form_for @session_form, url: sessions_path, html: { class: 'form-signin' } do |f|
            /   = f.input :email, input_html: { autofocus: true }
            /   = f.input :password, as: :password
            /   = link_to "Register As A New User", new_user_path
            /   %br
            /   %br
            /   = f.submit "Login", class: "btn btn-primary btn-block"

            
= javascript_include_tag "application"        

#reset_password_modal.modal.fade{tabindex: "-1", role: "dialog", aria: {labelledby: "Password Reset", hidden: true}}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: "button", data: {dismiss: "modal"}, aria: {hidden: true}} &times;
        %h4.modal-title Password Recovery
      .modal-body
        / = form_for :recover, :url => {:controller => "users", :action => "recover"} do |f|
        /   .form_group
        /     = f.label :email, "Email", class: "control-label"
        /     = f.text_field :email, class: "form-control"
        /   %br
        /   = f.submit "Reset Password", class: "btn btn-primary btn-block"

:css
  body { 
  //background: url('http://www.24hourtranslation.com/wp-content/uploads/2014/07/teaching-chinese.jpg') no-repeat center center fixed; 
  background: url('http://res.cloudinary.com/nara/image/upload/v1458031848/teaching-chinese-crop_l5yrmk.jpg') no-repeat center center fixed;
   -webkit-background-size: cover;
   -moz-background-size: cover;
   -o-background-size: cover;
   background-size: cover;
  }
  
  .panel-default {
   opacity: 0.9;
   margin-top:30px;
  }
  .form-group.last {
   margin-bottom:0px;
  }

  #map-canvas {
    width: 100%; 
    height: 300px;
    margin: 0;
    padding: 0px;
  }

coder2/app/views/users/_form.html.haml
= simple_form_for @user do |f|
	- if @user.errors.any?
		#error_explanation
			%h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
			%ul
				- @user.errors.full_messages.each do |msg|
					%li= msg

	.col-sm-4
		%h4 
			Required information
		= f.input :email, input_html: { value: @user.email, autofocus: true }, label: "Email*"

		= f.input :username, label: "Company Name*"

		= f.input :new_password, as: :password, label: "Password*"

		= f.input :new_password_confirmation, as: :password, label: "Confirm Password*"

		= f.input :address, label: "Street Address*"

    
	.col-sm-8
		%h4
			You can add the information in this column later
		= f.input :phone, label: "Phone"

		= f.input :city, label: "City"

		%strong Country
		= f.country_select('country')
		%br
		%br

		= f.input :about, as: :text, label: "Description"

	.actions
		= f.submit 'Save'

coder2/app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

coder2/app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
      %tr
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

coder2/app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

coder2/app/views/users/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path